### ISSUE TITLE
bannertool-linux64 fails GLIBCXX_3.4.21 not defined in file libstdc++.so.6

### ISSUE THREAD

**Issue by Theyrealone** [Steveice10/buildtools#12]
buildtools//3ds/bannertool-linux64: relocation error: buildtools//3ds/bannertool-linux64: symbol _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
	make: *** [build/banner.bnr] Error 127

yet bannertool-linux from https://github.com/Steveice10/buildtools/commit/cbda9a6b87292341f33f56099ac34894a58fe133 (referenced by https://github.com/Steveice10/citrus/commit/1f0b80b7135f42e1359c6f5c9e62bd3a109ec2aa ) works.
haven't checked whether  it stops working later.

Is this a problem with my environment or a bug?
edit: when using bannertool-linux from source ( https://github.com/Steveice10/bannertool/commit/55f34cfc5444bb23addab606255f3534f3c16cec ) it also works fine.

**Comment by Steveice10** [comment]
Working fine here. Check your environment.
