### ISSUE TITLE
zip: command not found

### ISSUE THREAD

**Issue by Favna** [Steveice10/buildtools#13]
While doing some testing after having updated my buildtools submodule I get the error `/bin/sh: line 1: zip: command not found` every time I run `make`. While a working normal `.cia` is still created, it then does proceed to remove the `.smdh` file resulting in having to build this manually to go with the `.3dsx`. 

The make log:

```
Building for 3DS...
build/3ds-arm/source/console.o
build/3ds-arm/source/ftp.o
build/3ds-arm/source/main.o
output/3ds-arm/FTPDB.elf
build/3ds-arm/meta.smdh
output/3ds-arm/3ds/FTPDB/FTPDB.3dsx
build/3ds-arm/banner.bnr
build/3ds-arm/icon.icn
output/3ds-arm/FTPDB.3ds
output/3ds-arm/FTPDB.cia
FTPDB.zip
/bin/sh: line 1: zip: command not found
make: *** [FTPDB.zip] Error 127
rm build/3ds-arm/meta.smdh build/3ds-arm/banner.bnr build/3ds-arm/icon.icn
```

---

And the makefile used for this build (raw from my repo)

[Makefile](https://raw.githubusercontent.com/Favna/FTPDB/master/Makefile)

The full source code can be found here: https://github.com/Favna/FTPDB

---

I suppose the error resides somewhere in the creation of the output_zip but for the world of me I cannot find it especially since it says "line 1" which is .. well obviously false. I have also tried it without specifying any output_zip in my own makefile but to no avail.

**Comment by Steveice10** [comment]
The main issue is simply that you don't have the zip command. However, do note that the SMDH is always deleted. For a long time now, the 3DSX format has supported embedding the SMDH into the 3DSX file, so a separate SMDH file is not needed.

**Comment by Favna** [comment]
Ugh of course. Got it now after installing Zip for Windows from GnuWin32 and adding that to PATH. Thanks for pointing me towards the obvious ^^"
