### ISSUE TITLE
Optionally allow different C++/C standards

### ISSUE THREAD

**Issue by phijor** [Steveice10/buildtools#14]
I'm currently building a project that uses features that are from C++14 and are supported by the compiler/libc++, yet `buildtools` forces me to use `-std=gnu++11`.

Could you imagine adding something along the lines of...

```
diff --git a/make_base b/make_base
index 4f89a8c..de4276a 100644
--- a/make_base
+++ b/make_base
@@ -376,8 +376,11 @@ endif
 
 # FINAL COMMON SETUP #
 
-CC_FLAGS := $(COMMON_CC_FLAGS) -std=gnu99
-CXX_FLAGS := $(COMMON_CC_FLAGS) -std=gnu++11
+CC_STD ?= -std=gnu99
+CXX_STD ?= -std=gnu++11
+
+CC_FLAGS := $(COMMON_CC_FLAGS) $(CC_STD)
+CXX_FLAGS := $(COMMON_CC_FLAGS) $(CXX_STD)
 
 ifneq ($(EXTRA_OUTPUT_FILES),)
     EXTRA_OUTPUT_COPY_CMD := cp -r $(EXTRA_OUTPUT_FILES) $(OUTPUT_DIR)

```

...to `make_base`? That would allow for different standards to be used by setting `$(CC_STD)` or `$(CXX_STD)`.

**Comment by Steveice10** [comment]
Added BUILD_FLAGS_CC and BUILD_FLAGS_CXX
