### ISSUE TITLE
[Question] vshader issues when porting ctrcommon to buildtools

### ISSUE THREAD

**Issue by Favna** [Steveice10/buildtools#15]
Since GBATemp is down at time of writing I figured I'd shoot this question as a github issue. I'm trying to port [Nanquitas BootNTR Selector](https://github.com/Nanquitas/BootNTR) from using ctrcommon to buildtools and I got it nearly all correct I think but whenever I run `make` with buildtools I get the following error, which I do not get when using a clean download of the repo. 

```
Building for 3DS...
build/3ds-arm/source/vshader.shbin.c
build/3ds-arm/source/vshader.shbin.o
build/3ds-arm/source/appInfo.o
build/3ds-arm/source/button.o
build/3ds-arm/source/common_functions.o
build/3ds-arm/source/config.o
build/3ds-arm/source/draw.o
source/draw.c: In function 'sceneInit':
source/draw.c:152:53: error: 'vshader_shbin_size' undeclared (first use in this function)
  vshader_dvlb = DVLB_ParseFile((u32*)vshader_shbin, vshader_shbin_size);
                                                     ^
source/draw.c:152:53: note: each undeclared identifier is reported only once for each function it appears in
make: *** [build/3ds-arm/source/draw.o] Error 1
rm build/3ds-arm/source/vshader.shbin.c
```

The make output from a clean download is: https://hastebin.com/jugebozuke.swift

The makefile I have for buildtools right now is: https://hastebin.com/mowawodili.makefile

As a side question, I can't find any references in buildtools how it would handle previously created `bnr` files, I just assumed defining it as `BANNER` would do but if that's wrong please also let me know.

**Comment by Steveice10** [comment]
Try chaning size to len.

**Comment by Favna** [comment]
Sorry, but could you clarify? I can't quite find what you mean with that.

**Comment by Steveice10** [comment]
"vshader_shbin_size". Try changing the "size" to "len".

**Comment by Favna** [comment]
Seems to be the thing that solves it indeed. I'm having some portlibs issues right now that I have to fix before the building will work (it is failing on libpng stuff). I'll close the issue with this comment.

(damn Cell9 it would've been great if you had mentioned dependancies)
